USE ROLE ACCOUNTADMIN;
CREATE DATABASE FINTECH;
USE DATABASE FINTECH;
CREATE SCHEMA RAW;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS RAW_TRANSACTIONS(
    transaction_id STRING,
    user_id STRING,
    timestamp DATETIME,
    amount FLOAT,
    currency STRING,
    merchant STRING,
    merchant_category STRING,
    card_type STRING
);

CREATE OR REPLACE FILE FORMAT CSV_FILE_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    RECORD_DELIMITER = '\n'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL','')
    EMPTY_FIELD_AS_NULL = TRUE
;

CREATE OR REPLACE STAGE FINTECH.RAW.MY_S3_STAGE
  URL = 's3://aws-s3-fintech-125869386643-eu-north-1-an/'
  FILE_FORMAT = (FORMAT_NAME = FINTECH.RAW.CSV_FILE_FORMAT)
  CREDENTIALS = (
    AWS_KEY_ID = '{{ env.get("AWS_ACCESS_KEY_ID") }}' 
    AWS_SECRET_KEY = '{{ env.get("AWS_SECRET_ACCESS_KEY") }}'
  );
    
