USE ROLE ACCOUNTADMIN;
CREATE DATABASE FINTECH;
USE DATABASE FINTECH;
CREATE SCHEMA RAW;
USE SCHEMA RAW;

CREATE TABLE RAW_TRANSACTIONS(
    transaction_id STRING,
    user_id STRING,
    timestamp DATETIME,
    amount FLOAT,
    currency STRING,
    merchant STRING,
    merchant_category STRING,
    card_type STRING
);

CREATE OR REPLACE FILE FORMAT CSV_FILE_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    RECORD_DELIMITER = '\n'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL','')
    EMPTY_FIELD_AS_NULL = TRUE
;

CREATE OR REPLACE STAGE S3_EXT_STAGE
    URL = 'MY S3 BUCKET URL'
    FILE_FORMAT = CSV_FILE_FORMAT;
